import { useNavigate, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import SEOHead from "@/components/SEOHead";

const Privacy = () => {
  const navigate = useNavigate();

  return (
    <>
      <SEOHead 
        title="Privacy Policy | Prometheus"
        description="Read the Prometheus privacy policy. Learn how we handle your data, our security practices, and your rights as a user of our AI companion platform."
        keywords="privacy policy, data protection, terms of service, Prometheus AI"
        canonicalUrl="https://prometheus.lovable.app/privacy"
      />
      <div className="min-h-screen bg-background p-4">
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-3xl font-serif font-bold">Privacy Policy</h1>
            <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Introduction</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              Prometheus is a free-to-use AI companion designed to help you connect with your higher self 
              through meaningful conversations and visual creation. This privacy policy outlines how we 
              handle your data and the terms of use for our service.
            </p>
            <p className="font-semibold text-amber-600 dark:text-amber-400">
              You must be 18 years or older to use Prometheus. By using this service, you confirm that you 
              meet this age requirement.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Use at Your Own Risk & Disclaimer</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              Prometheus is provided as a free tool for personal growth and exploration. By using this 
              service, you acknowledge and accept the following:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>No Liability:</strong> We are not held responsible for any content, conversations, 
                actions, or consequences arising from your use of this application. All interactions are at 
                your sole discretion and risk.
              </li>
              <li>
                <strong>No Warranty:</strong> This service is offered without warranty of any kind, express 
                or implied, including but not limited to warranties of accuracy, reliability, or fitness for 
                any particular purpose.
              </li>
              <li>
                <strong>AI-Generated Content:</strong> All AI responses are generated by machine learning 
                models and should not be considered professional medical, legal, financial, or therapeutic 
                advice. Always consult qualified professionals for such matters.
              </li>
              <li>
                <strong>User Responsibility:</strong> You are solely responsible for all content you create, 
                share, or discuss within the application. Exercise sound judgment and discretion in all 
                interactions.
              </li>
              <li>
                <strong>Service Availability:</strong> We operate without dedicated funding, which means 
                service availability, features, and functionality may change or be discontinued without notice.
              </li>
              <li>
                <strong>Age Requirement:</strong> This service is intended for users 18 years or older. Use 
                by minors is strictly prohibited.
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Data Collection and Usage</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              To provide our services, we collect and process the following information:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Account Information:</strong> Email address and username for authentication purposes
              </li>
              <li>
                <strong>Conversation Data:</strong> Your chat messages and interactions with the AI to provide 
                personalized responses and improve the service
              </li>
              <li>
                <strong>Uploaded Content:</strong> Images you choose to share during conversations for AI analysis 
                and response generation
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Data Security</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              We implement industry-standard security measures to protect your data, including:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Encrypted data transmission using HTTPS</li>
              <li>Secure authentication through established providers</li>
              <li>Access controls to limit data exposure</li>
            </ul>
            <p>
              However, no method of transmission over the internet is 100% secure. While we take reasonable 
              precautions, we cannot guarantee absolute security of your information.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Third-Party Services</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              Prometheus integrates with third-party services to provide its functionality:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Authentication:</strong> We use secure authentication providers including Google OAuth
              </li>
              <li>
                <strong>AI Services:</strong> Your conversations are processed by AI models to generate responses
              </li>
              <li>
                <strong>Storage:</strong> Your data is securely stored using cloud infrastructure
              </li>
            </ul>
            <p>
              These services have their own privacy policies and terms of service. We encourage you to 
              review them.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Your Rights</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>You have the right to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Access your personal data stored in our system</li>
              <li>Request deletion of your account and associated data</li>
              <li>Export your conversation history</li>
              <li>Opt out of data collection by ceasing use of the service</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Limitation of Liability</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              By using Prometheus, you acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                The service is provided "as is" without any guarantees of availability, accuracy, or fitness 
                for a particular purpose
              </li>
              <li>
                We are not liable for any damages, losses, or consequences arising from your use of the service
              </li>
              <li>
                The AI-generated content is for informational and exploratory purposes only and should not 
                replace professional advice
              </li>
              <li>
                We reserve the right to modify, suspend, or discontinue the service at any time
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Changes to This Policy</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              We may update this privacy policy from time to time. Changes will be reflected by updating 
              the "Last updated" date at the top of this page. Continued use of Prometheus after any 
              changes constitutes acceptance of the updated policy.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Contact</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              If you have questions about this privacy policy or your data, please contact us through 
              the settings page in the application.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Related Policies</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none">
            <p>
              Please also review our{" "}
              <Link to="/terms" className="text-primary hover:underline">
                Terms of Service
              </Link>{" "}
              to understand our rules of conduct and AI protection policies.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
    </>
  );
};

export default Privacy;
